added model Badges
Aleksandr-Slap/TestGuru pull request #23
Opened 2022-04-23 17:11 UTC by Aleksandr-Slap

2022-05-02 16:53 UTC, BubuntuClu requested changes

2022-05-02 16:53 UTC, BubuntuClu commented on app/controllers/badges_controller.rb
> +    @user_badges = Badge.where(id: current_user.badges.ids.uniq)
используй ассоциацию, чтобы получить баджи пользователя

2022-05-02 16:53 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      CheckBadge.new(@test_passage).call
вызывать серис стоит только в случае успешного прохождения теста

2022-05-02 16:53 UTC, BubuntuClu commented on app/models/test_passage.rb
> +      self.passed = true if passed_the_test?
этого тут не должно быть. этот метод только принимает ответы. за флаг прохождения он не должен отвечать

2022-05-02 16:53 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :my_badges,class_name: 'Badge', foreign_key: :user_id
это зачем?

2022-05-02 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    @user = User.find(@test_passage.user_id)
используй ассоциации, не пиши руками запросы

2022-05-02 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    if @test_passage.passed_the_test? && test_passage_first?
если количество проверок в баджах будет расти, то и этот метод будет расти бесконечно. надо подумать и переделать, чтобы метод не зависел от количества правил

2022-05-02 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +      @badge = Badge.last
когда ты добавишь новый бадж, этот код сломается. никогда не завязывайся на порядок и на хардкод id

2022-05-02 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +      @badge = Badge.find(2)
это хардкод айдшника, та кделать нельзя. у тебя может не быть такого id в бд

2022-05-02 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +  def test_passage_first?
думаю что условия проверки успешности должно быть в внутри метода, а не доп условием для проверки

2022-05-02 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    Test.show_tests("Backend").ids
название категории и уровень теста должны браться из настроек баджа. чтобы можно было через бадж управлять за что давать награду.

2022-05-02 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    TestPassage.where(test_id: one_level_tests(find_level)).where(user_id: @test_passage.user_id).where(passed: true).count >= one_level_tests(find_level).count
условие сравнения неправильно. если в левой части больше чем в правой, значит не все тесты уровня пройдены

2022-05-02 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    TestPassage.where(test_id: backend_category).where(user_id: @test_passage.user_id).where(passed: true).count >= backend_category.count
неправильное сравнение

2022-05-02 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +      @user.badges.push(@badge)
эта строка встречается несколько раз в этом методе. надо отрефакторить

2022-05-02 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    if @test_passage.passed_the_test? && test_passage_first?
подсказка, нужно пойти через перебор баджей

2022-05-02 16:53 UTC, BubuntuClu commented on app/views/badges/index.html.erb
> +<% @user_badges.each do |badge| %>
а тут почему не используешь паршиал баджа? код вроде бы одинаковый

2022-05-04 08:12 UTC, Aleksandr-Slap commented on app/models/user.rb
> +  has_many :my_badges,class_name: 'Badge', foreign_key: :user_id
Абсолютно незачем!

2022-05-04 08:15 UTC, Aleksandr-Slap commented on app/controllers/badges_controller.rb
> +    @user_badges = Badge.where(id: current_user.badges.ids.uniq)
Понял - исправил

2022-05-04 09:30 UTC, Aleksandr-Slap commented on app/models/test_passage.rb
> +      self.passed = true if passed_the_test?
Исправил с помощью update_attribute для обхода колбеков(спасибо)

2022-05-04 09:31 UTC, Aleksandr-Slap commented on app/controllers/test_passages_controller.rb
> +      CheckBadge.new(@test_passage).call
Сделал

2022-05-04 09:34 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    @user = User.find(@test_passage.user_id)
Понял - сделал
@user = @test_passage.user

2022-05-04 09:39 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    if @test_passage.passed_the_test? && test_passage_first?
Тут не понял - надо подумать!

2022-05-04 09:49 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +      @badge = Badge.last
Тут видимо нужно добавить атрибут, например: 

"rule" тип данных "string" и конкретно для этого баджа будет выглядеть так:

rule: "passed_one_level_tests"

и поиск соответственно:   @badge = Badge.where(rule: "passed_one_level_tests")

Правильно?

2022-05-04 09:50 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +      @badge = Badge.find(2)
Тут видимо так же нужно сделать...через доп. атрибут(rule)

2022-05-04 09:50 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +  def test_passage_first?
Исправил

2022-05-04 09:59 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    Test.show_tests("Backend").ids
С трудом понимаю(

Добавить атрибуты для баджа (2) 

category: "Backend"
level: 1

Так?

Мысли в слух: Мне нужно добавить кучу атрибутов в бажд, которые админ будет заполнять, а какие то оставлять пустыми(если они не нужны) и на этом как то можно будет основывать правила выдачи...

2022-05-04 10:03 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    TestPassage.where(test_id: one_level_tests(find_level)).where(user_id: @test_passage.user_id).where(passed: true).count >= one_level_tests(find_level).count
Кажись понял, я ищу запись конкретного пользователя и его тест в таблице, но не проверяю является ли этот  test_passage пройденным (passed: true)

2022-05-04 10:04 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    TestPassage.where(test_id: one_level_tests(find_level)).where(user_id: @test_passage.user_id).where(passed: true).count >= one_level_tests(find_level).count
TestPassage.where(user_id: @test_passage.user_id).where(test_id: @test_passage.test_id).where(passed: true).count == 1

2022-05-04 10:09 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    TestPassage.where(test_id: backend_category).where(user_id: @test_passage.user_id).where(passed: true).count >= backend_category.count
По моему правильное) Пользователь же может получать один и тот же бэйдж более одного раза.

Поэтому если в таблице TestPassage количество записей соответствующих условию больше и равно количеству тестов конкретной категории, то он получает бадж. Можно сделать == но тогда бадж можно получить только один раз.

2022-05-04 10:14 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +      @user.badges.push(@badge)
Добавил:

def get_a_badge
  @user.badges.push(@badge)
end

заменил строки на метод

2022-05-04 10:20 UTC, Aleksandr-Slap commented on app/views/badges/index.html.erb
> +<% @user_badges.each do |badge| %>
<% if @user_badges.present? %>
  <% @user_badges.each do |badge| %>
    <p>
      <%= render @badges %>
    </p>  
  <% end %>
  
  Так работает как надо!

2022-05-04 13:43 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    if @test_passage.passed_the_test? && test_passage_first?
Не понимаю, как это сделать.

2022-05-04 13:46 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +      @badge = Badge.last
Но в тот же момент, не будет же админ "руками" писать "passed_one_level_tests". Нужно, что бы он выбирал, из списка, как при создании теста выбираешь его категорию. А тут уже нужна модель правил

2022-05-04 13:48 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +      @badge = Badge.find(2)
Может можно искать по атрибуту title?

@badge = Badge.where(title: "Просто красава")

2022-05-04 15:32 UTC, BubuntuClu commented on app/services/check_badge.rb
> +      @badge = Badge.last
руками не будет, будет выбирать из списка. список либо хардкодом где-то у тебя прпоисан, либо делать модель под правила

2022-05-04 15:32 UTC, BubuntuClu commented on app/services/check_badge.rb
> +      @badge = Badge.find(2)
и ты каждый бадж хочешь искать отдельно? и будет у тебя 50 запросов в БД. подумай как можно за раз достать все баджи и имея все баджи на руках, реализовать проверку их критериев

2022-05-04 15:33 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    Test.show_tests("Backend").ids
нет, атрибута будет всего два. rule и value. в один пишется правило для баджа(какой метод будет отвечать за проверку условий прохождений), во второе пишется значение параметра для правила

2022-05-04 15:35 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    TestPassage.where(test_id: backend_category).where(user_id: @test_passage.user_id).where(passed: true).count >= backend_category.count
сейчас если у тебя пройти один тест 5 раз успешно, а в категории будет всего 3 теста, то ты получишь награду,  хотя не должен, так как ты не прошел все тесты категории

если будешь проверять через id тестов, а не через количество прохождений, то не будет ограничений на выдачу. и будет условие работать через ==.

2022-05-06 19:03 UTC, BubuntuClu requested changes

2022-05-06 19:03 UTC, BubuntuClu commented on app/controllers/badges_controller.rb
> +  def create
создавать баджи должен только админ. для пользователя должен быть доступен только `index` метод

2022-05-06 19:03 UTC, BubuntuClu commented on app/models/badge.rb
> +  belongs_to :user, optional: true
зачем тут эта связь? что она тебе дает?

2022-05-06 19:03 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    @badge = badge
зачем ты из одной переменной перекладываешь в другую?
что мешает сделать просто `@user.badges.push(badge)`?

2022-05-06 19:03 UTC, BubuntuClu commented on app/views/badges/index.html.erb
> +  <% @user_badges.each do |badge| %>
ты вроде хотел заменить это на паршиал

2022-05-06 19:03 UTC, BubuntuClu commented on db/migrate/20220505093731_add_two_column_to_badges.rb
> +    add_column :badges, :rule_name, :string
ты находишься в ветке, которой еще ни у кого нет. не надо плодить миграции на исправление/добавление в таблицу. откати миграцию создания таблицы и там добавь все что надо

2022-05-06 19:03 UTC, BubuntuClu commented on db/migrate/20220423145557_create_badges.rb
> +      t.references :user, foreign_key: true
зачем эта связь?

2022-05-06 19:03 UTC, BubuntuClu commented on app/services/check_badge.rb
> +  def passed_all_back_end?(category)
нейминг метода уже не подходит

2022-05-07 12:27 UTC, Aleksandr-Slap commented on app/controllers/badges_controller.rb
> +  def create
Понял

2022-05-07 12:27 UTC, Aleksandr-Slap commented on app/models/badge.rb
> +  belongs_to :user, optional: true
Да, связь с юзером вообще не нужна

2022-05-07 12:28 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    @badge = badge
Понял)

2022-05-07 12:34 UTC, Aleksandr-Slap commented on db/migrate/20220505093731_add_two_column_to_badges.rb
> +    add_column :badges, :rule_name, :string
Ок!

2022-05-07 12:34 UTC, Aleksandr-Slap commented on db/migrate/20220423145557_create_badges.rb
> +      t.references :user, foreign_key: true
Как уже говорили - незачем!

2022-05-07 16:53 UTC, BubuntuClu requested changes

2022-05-07 16:53 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +    @user_badges = current_user.badges
не уверен что это надо админу

2022-05-07 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +       .uniq.count == test_ids.count && test_category_id == 25
зачем тут проверка `test_category_id == 25`? в параметре может быть любая категория и она скорее всего не будет иметь id 25. и в очередной раз ты делаешь хардкод на ID. вот задеплой этот код. есть у тебя ID такой категории на проде? я думаю нет и этот бадж не будет выдаваться никогда

2022-05-07 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    test_category_id = Test.find(@test_passage.test_id).category_id
это что за покемон? 
используй ассоциации, у тебя есть тест в пассаже `@test_passage.test.category_id`. уже далеко не первый раз пишу тебе про ассоциации, пора бы уже самому исправлять свои такие ошибки

2022-05-07 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    TestPassage.where(test_id: test_ids)
помести весь этот запрос в какую-нибудь переменную. сравнение теряется в массе строк кода.
сделай просто сравнение двух переменных

2022-05-07 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +  def passed_one_level_tests?(level)
для этого метода все те же самые замечания что и для категорий

2022-05-07 16:53 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    TestPassage.where(user_id: @test_passage.user_id)
`TestPassage.where(user_id: @user.id, test_id: @test_passage.test_id).count == 1`

@test_passage.test - это тоже можно сохранить в инициализации как @test, и запросы станут "легче"

2022-05-07 16:53 UTC, BubuntuClu commented on app/views/admin/badges/index.html.erb
> +  <% @user_badges.each do |badge| %>
на паришал переделай

2022-05-08 08:24 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +       .uniq.count == test_ids.count && test_category_id == 25
Понял!

2022-05-08 08:25 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    test_category_id = Test.find(@test_passage.test_id).category_id
Понял(

2022-05-08 08:25 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    TestPassage.where(test_id: test_ids)
Принято!

2022-05-08 08:26 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    TestPassage.where(user_id: @test_passage.user_id)
Понял!

2022-05-08 08:26 UTC, Aleksandr-Slap commented on app/views/admin/badges/index.html.erb
> +  <% @user_badges.each do |badge| %>
Уже!

2022-05-11 17:07 UTC, BubuntuClu requested changes

2022-05-11 17:07 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    passed_tests_of_one_category == test_ids.count && test_category_id == id_category
1 - `test_category_id == id_category` если ты делаешь подобную лоигку, то имеет смысл делать проверку такого рода
`return if @test.category.title != category` в самом начале метода проверки. так ты разгрузишь БД. в твоем случае ты делаешь все вычисления и в самом конце узнаешь что категории не совпадают и все твои вычисления не пригодились

2 - зачем тебе искать id категории когда ты можешь title сравнить? `id_category = Category.find_by(title: category).id` создаешь один лишний запрос к БД

2022-05-11 17:07 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    passed_tests_of_the_same_level == test_ids.count && test_level_id == level.to_i
1 - проверку уровня теста и уровня из баджа делай в самом начале кода метода
2 - `test_level_id = @test.level`, почему этот объект называется _id? там нет никаого id

2022-05-11 17:07 UTC, BubuntuClu commented on app/views/admin/badges/index.html.erb
> +      <%= render @badges %>
неправильно сделал. это другая коллекция, не та, по которой итерируешь + у тебя выведутся баджи столько раз солько наград получил пользователь. нужно убрать итерацию

2022-05-11 17:07 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    number_of_passes = TestPassage.where(user_id: @user.id)
`where(user_id: @user.id, test_id: @test_id)`, объединяй условия `where` в одну операцию, зачем лишний код писать

2022-05-11 17:07 UTC, BubuntuClu commented on app/services/check_badge.rb
> +    passed_tests_of_one_category == test_ids.count && test_category_id == id_category
`.where(passed: true)` выглядит как кандидат на скоуп

2022-05-12 15:55 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    passed_tests_of_one_category == test_ids.count && test_category_id == id_category
Сделано

2022-05-12 15:56 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    passed_tests_of_the_same_level == test_ids.count && test_level_id == level.to_i
Понял - сделал

2022-05-12 15:56 UTC, Aleksandr-Slap commented on app/views/admin/badges/index.html.erb
> +      <%= render @badges %>
За это отдельное спасибо!

2022-05-12 15:56 UTC, Aleksandr-Slap commented on app/services/check_badge.rb
> +    number_of_passes = TestPassage.where(user_id: @user.id)
Принято - сделано!

2022-05-14 09:12 UTC, merged