add validation and scope methods
Aleksandr-Slap/TestGuru pull request #7
Opened 2021-07-28 13:23 UTC by Aleksandr-Slap

2021-07-28 18:38 UTC, BubuntuClu requested changes

2021-07-28 18:38 UTC, BubuntuClu commented on app/models/answer.rb
> +    if Answer.where(question_id: question_id).size >= 4
`Answer.where(question_id: question_id)` это замени на `question.answers`. привыкай использовать ассоциации

2021-07-28 18:38 UTC, BubuntuClu commented on app/models/answer.rb
> +	validate :limit_answers
валидирвать стоит только во время создания `on: :create`

2021-07-28 18:38 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :sorting_categories, -> (name_category) {self.joins(:category).where(categories: {title: name_category}).order('tests.title DESC').pluck('tests.title')}
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2021-07-28 18:38 UTC, BubuntuClu commented on app/models/test.rb
> +                    uniqueness: true
связка полей title+level должна быть уникальная, а не каждое в отдельности

2021-07-28 18:38 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true
валидации идут до методов.

этот список валадции можно объединить в одну строку

2021-07-28 18:38 UTC, BubuntuClu commented on app/models/user.rb
> +
линяя пустая строка

2021-07-28 18:38 UTC, BubuntuClu commented on app/models/user.rb
> +	end
куда-то end уехал

2021-07-28 18:38 UTC, BubuntuClu commented on db/migrate/20210627092550_create_users.rb
> +      t.string :email, null: false
нельзя править миграции которые уже смержили. надо убрать все изменения из миграций, которые ты внес и через новые миграции вносить изменения

2021-07-28 18:38 UTC, BubuntuClu commented on db/migrate/20210627091818_create_answers.rb
> +      t.boolean :correct, null: false, default: false
тоже самое про миграцию, так нельзя делать. правки вносить только через новую миграцию

2021-07-28 18:38 UTC, BubuntuClu commented on app/models/test.rb
> +                    uniqueness: true
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный составной индекс надо

2021-07-28 19:33 UTC, Aleksandr-Slap commented on app/models/answer.rb
> +    if Answer.where(question_id: question_id).size >= 4
Блин! У меня как-будто это не работало! Выбрасывало: undefine method "answers"  
Всё работает!

2021-07-28 19:36 UTC, Aleksandr-Slap commented on app/models/answer.rb
> +    if Answer.where(question_id: question_id).size >= 4
Пипец, я  и строку выше удалил: question_id = self.question.id
И все отлично работает! Как так!

2021-07-29 11:26 UTC, Aleksandr-Slap commented on app/models/test.rb
> +  scope :sorting_categories, -> (name_category) {self.joins(:category).where(categories: {title: name_category}).order('tests.title DESC').pluck('tests.title')}
Не сразу, но понял!

2021-07-29 19:03 UTC, BubuntuClu requested changes

2021-07-29 19:03 UTC, BubuntuClu commented on app/models/answer.rb
> +  validate :limit_answers, on: :create
а чего весь код прыгает? настрой замену табов на 2 пробела чтобы такого не было

2021-07-29 19:03 UTC, BubuntuClu commented on app/models/answer.rb
> +
куча лишних пустых строк

2021-07-29 19:03 UTC, BubuntuClu commented on app/models/category.rb
> +	scope :all_categories, -> { all.order('title') }
all тут не надо

2021-07-29 19:03 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :show_tests, -> { self.joins(:category).all }
self/all не надо. where надо поместить в скоуп, у тебя будет скоуп с параметром

2021-07-29 19:03 UTC, BubuntuClu commented on app/models/user.rb
> +	end
все еще ездит

2021-08-02 11:05 UTC, merged