incorrect display of new.html.erb
Aleksandr-Slap/TestGuru pull request #8
Opened 2021-08-02 16:12 UTC by Aleksandr-Slap

2021-08-10 17:21 UTC, BubuntuClu requested changes

2021-08-10 17:21 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    set_test
кажется, ты упустил смысл методов `before_action`. метод у тебя вызывается до вызова экшена. в самом экшене его не надо вызывать

2021-08-10 17:21 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.create(question_params)
Параметры с фронта могут быть не валидные, это надо учитывать
```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end
```

2021-08-10 17:21 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.find_by(id:params[:id])
это новый вопрос, как ты его ищешь по id?

2021-08-10 17:21 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id]) || record_not_found
а почему тут не через тест ищешь как везде?

2021-08-10 17:21 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<%= form_with model: [ @test, @test.questions.build ] do |form| %>
ты в экшене `new` объявил объект вопроса, его тут используй

2021-08-10 17:21 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
добавь опцию `shallow: true`, посмотри как изменятся роуты и адаптируй код

2021-08-10 17:21 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.find(params[:id]) || record_not_found
у тебя есть обработчик, который перехватывает ошибку поиска, зачем тут `|| record_not_found`?

2021-08-10 17:21 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.find_by(id:params[:id])
используй `find` чтобы получать ошибку при поиске, чтобы твой обработчик работал. `find_by` не выбрасывает исклчюения

2021-08-11 12:53 UTC, Aleksandr-Slap commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.find_by(id:params[:id])
> это новый вопрос, как ты его ищешь по id?

Ну да, бред!

2021-08-11 12:57 UTC, Aleksandr-Slap commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.find(params[:id]) || record_not_found
Читал статью где так делали. 
Удалил и всё работает!)

2021-08-11 14:38 UTC, Aleksandr-Slap commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id]) || record_not_found
Поменял было на @test.questions.find_by(id:params[:id]), но после использовал shallow: true  и оставил как было

2021-08-12 17:31 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    def record_not_found
ты поместил этот метод в общий для всех контроллеров источник наследования. а в тексте у тебя написано 
"render plain: "404 No question found", status: 404". когда будет tests_controller и он не будет найден, у тебя будет текст про вопрос, что неправильно. вынеси эту логику из ApplicationController в контроллер вопросов

2021-08-12 17:31 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
этот метод у тебя дублируется. вынеси его тоже в колбэк

2021-08-12 17:31 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.create(question_params)
если ты делаешь `create`, то ты сохраняешь в БД объект. после этого `save` пытается повтороно сохранить объект. таким образом ты делаешь лишний запрос в БД

2021-08-12 19:49 UTC, merged